default:	
	gcc -pthread -o makeBreadEx.o exclusive_access_inventory.c Inventory_BinTree.c
cli:
	gcc -pthread -o	testCli.o cli.c 
run:
	./makeBreadEx.o
runCli:
	./testCli.o
clean:
	rm *.o rm
rm:
	rm *.o
