default:	
	gcc -pthread -o makeBreadEx.o exclusive_access_inventory.c Inventory_BinTree.c
cli:
	gcc -pthread -o	testCliAndTree.o cli.c Inventory_BinTree.c
run:
	./makeBreadEx.o
clean:
	rm *.o rm
rm:
	rm *.o
